### ISSUE TITLE
Automatic assigning of z-index.

### ISSUE THREAD

**Issue by michahell** [ManifestWebDesign/angular-gridster#259]
Hi, for a node-webkit app i'm working on I'd like to have all my gridster items have a stacking z-index.
I'd like to use the style attribute for this, but gridster uses this itself to set some style rules at runtime. How should I do this? The z-index is to make sure that absolute positioned elements inside each gridster item overlay the gridster box beneath it.

So to overcome this:
http://s16.postimg.org/j67cee4d1/Screen_Shot_2015_04_26_at_01_40_54.png

I want to achieve this (manually set z-index on gridster item):
http://s15.postimg.org/iom40e6gb/Screen_Shot_2015_04_26_at_02_31_39.png

like so: ```style="z-index: calc(999-$index);"``` where ```$index``` is the index of an ng-repeat of gridster items.

**Comment by danomatic** [comment]
I believe there are a few ways to get what you want:

## 1
Use some kind of style calculation on your gridster items.  In your case, it sounds like you actually want a higher z-index if the item row is lower.  This example does the opposite.
```html
    <div gridster="gridsterOpts">
        <ul>
            <li gridster-item="item" ng-repeat="item in standardItems" ng-style="{ 'z-index': gridsterItem.isMoving() ? 9999 : (5 + item.row * 10 + item.col) }"></li>
        </ul>
    </div>
```

## 2
Use a focus or click event to give a gridster item priority:
```html
    <div gridster="gridsterOpts" ng-init="selected = {}">
        <ul>
            <li gridster-item="item" ng-repeat="item in standardItems" ng-click="selected.item = item" ng-style="{ 'z-index': selected.item === item ? 999 : '' }"></li>
        </ul>
    </div>
```

## 3
Place your menu outside of the gridster elements, possibly attached to the end of the document.  This is more difficult in some regards, because you will have to do lot of attaching and detaching and positioning of that menu element.

Hopefully that helps.  Happy coding!

**Comment by michahell** [comment]
Hello @danomatic and thanks for your fast response! It's great to have so many options, the first one is right-on what i'd want, I completely forgot about ng-style! the second option you propose is good as well, the third and last not because in my case, I do not control the placement of the element I need to overlap, it's deep inside another component (ng-tags-input). Anyway, think it's as good as solved now, thanks again!
