### ISSUE TITLE
curColWidth property access problem

### ISSUE THREAD

**Issue by reidlai** [ManifestWebDesign/angular-gridster#300]
I have the following three lines in controllerA in order to access the width of each cell defined in gridster:

	var gridsterScope = angular.element("div[gridster]").scope();
	console.log(gridsterScope.gridster);
	console.log(gridsterScope.gridster.curColWidth);

I tried to monitor the output thru Chrome Developer Console.  I can see the second line and output the whole object including curColWidth (value is 116.4375).  My purpose is to use curColWidth to calculate actual gridsterItem actual width in px instead of number of cell.  However, I got undefined error at the third line.  I have no idea why can't access curColWidth property.  Anyone can help?

**Comment by danomatic** [comment]
I think you have a race condition.  In Chrome, when you console.log an Object, the tree that is displayed will synchronize with the object as it gets updated, so will see values that are set after the `console.log(gridsterScope.gridster)` call.  However, since curColWidget is initially undefined and it is not an object with keys that update, your console output stays undefined.

You probably just have to let another watch cycle run to get that value.
