### ISSUE TITLE
Gridster Nesting

### ISSUE THREAD

**Issue by tonybebber** [ManifestWebDesign/angular-gridster#95]
Just wondering if there is any way to have nested gridster instances using this directive? When I try this, the outer gridster instance works as expected, however the inner gridster  instance items are not sized properly on initialization and dragging/resizing them doesn't work.

Here is my template code...

        <div gridster="outerGridster.config">
            <ul>
                <li gridster-item="item" ng-repeat="item in outerGridster.items">
                    <div gridster="innerGridster.config">
                        <ul>
                            <li gridster-item="anotheritem" ng-repeat="anotheritem in innerGridster.items"></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>

And here is what I have in my controller...

    // setup for outer gridster instance...    
    $scope.outerGridster = {
        config: {
            columns: 4
        },
        items: [
            { sizeX: 2, sizeY: 1, row: 0, col: 0 },
            { sizeX: 2, sizeY: 1, row: 0, col: 2 },
            { sizeX: 2, sizeY: 1, row: 1, col: 0 },
            { sizeX: 2, sizeY: 1, row: 1, col: 2 }
        ]
    };

    // setup for inner gridster instance... 
    $scope.innerGridster = {
        config: {
            columns: 2
        },
        items: [
            { sizeX: 2, sizeY: 1, row: 0, col: 0 },
            { sizeX: 2, sizeY: 1, row: 0, col: 2 }
        ]
    };

Thanks for any help

**Comment by danomatic** [comment]
Closing this because nested grids should be working now.

**Comment by narigua** [comment]
Hi all, i corrected your link @tannerlinsley (you just forgot a ',' line 5 in JS) ;)

The problem on nested grid is that you need to think that your parent have X cols then child need to have less. I added this option in your example : http://codepen.io/narigua/pen/rOeWrV
You can see that you need to add a draggable zone because gridster can't understand which item you want to drag (sorry for my bad english).

Now for me, a question : How can i configure gridster options to fill automaticaly height with content inside ?
